#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
_share="${_bin}/../share"
source \
  "${_lib}/libcrash-bash/crash-bash"

_requirements() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    _check_cmd \
      "activity-launch" \
      "android-activity-utils"
    _check_cmd \
      "activity-focused" \
      "android-activity-utils"
  fi
}

# shellcheck disable=SC2034
_global_variables() {
  view_date=""
  view_target=""
  view_address=""
  view_port=""
  server_port=""
  view_password=""
  view_length=""
  poll_interval=""
  viewer_app=""
  server_app=""
  display_dim=""
  touch_disabled=""
  color=""
  quiet=""
}

_multivnc_opts() {
  _viewer_reverse_name='com.coboltforge.dontmind.multivnc'
  _viewer_helper_opts+=(
    -a
      "${_view_address}"
    -p
      "${_view_port}"
    -k
      "${_view_password}"
  )
}

_android_vnc_viewer() {
  local \
    _view_target="${1}" \
    _view_address="${2}" \
    _view_port="${3}" \
    _server_port="${4}" \
    _view_password="${5}" \
    _length="${6}" \
    _viewer_app="${7}" \
    _server_app="${8}" \
    _poll="${9}" \
    _dim="${10}" \
    _touch_disabled="${11}" \
    _cmd_opts=() \
    _opts=() \
    _viewer_reverse_name \
    _activity_launch_opts=() \
    _viewer_helper_opts=() \
    _conf
  shift \
    11
  _opts=(
    "$@"
  )
  _conf="$( \
    _get_conf_path)"
  if [[ "quiet" != "y" ]]; then
    _activity_launch_opts+=(
      -v
    )
    _viewer_helper_opts+=(
      -v
    )
  fi
  # _a="$( \
  #     _read_settings \
  #       "${_conf}" \
  #       "${_host}" \
  #       "port")"
  # 'net.sourceforge.opencamera' 'MainActivity'
  _activity_launch_opts+=(
    -L
      "${_length}"
  )
  if [[ "${_dim}" == "y" ]]; then
    _activity_launch_opts+=(
      -d
      -p
        "${_poll}"
    )
  fi
  if [[ "${_touch_disabled}" == "y" ]]; then
    _activity_launch_opts+=(
      -t
    )
  fi
  "_${_viewer_app}_opts"
  "${_viewer_app}-helper" \
    "${_viewer_helper_opts[@]}" \
    "add" \
    "${_view_target}" || \
    true
  activity-launch \
    "${_activity_launch_opts[@]}" \
    "${_viewer_reverse_name}" \
    "ui.VncCanvasActivity" || \
    true
}

_view_tunnel() {
  local \
    _dynssh_opts=()
  if [[ "${_server_port}" != "" ]]; then
    if [[ "${quiet}" != "y" ]]; then
      _dynssh_opts+=(
        -v
      )
    fi
    _dynssh_opts+=(
      -t
        "${view_target}"
      -l
        "${_view_port}"
      -r
        "${_remote_port}"
    )
    _run \
      "tunnel_${_view_target}" \
      "0" \
      "async" \
      dynssh \
        "${_dynssh_opts[@]}" -- \
        "${_view_target}" \
        "sleep ${_length}" || \
      true
  elif [[ "${_server_port}" == "" ]]; then
    true
  fi
}

_viewer_app_auto_detect() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    echo \
      'multivnc'
  fi
}

_server_app_auto_detect() {
  local \
    _os
  _os="$( \
    uname \
      -o)"
  if [[ "${_os}" == 'Android' ]]; then
    echo \
      'droidvnc'
  fi
}

_get_conf_path() {
  local \
    _dir \
    _conf
  _dir="${HOME}/.config/$(_get "app" "name")"
  _conf="${_dir}/$( \
    _get \
      "app" \
      "name").cfg"
  echo \
    "${_conf}"
}

_target_opts_auto_detect() {
  local \
    _cmd=() \
    _dynssh_opts=() \
    _credentials \
    _port \
    _password
  if [[ "${view_target}" != "" ]]; then
    _msg=(
      "getting credentials from"
      "target '${view_target}' server"
      "and server '${server_app}'" 
    )
    _msg_info \
       "${_msg[*]}"
    _dynssh_opts+=(
      -t
        "${view_target}"
    )
    _cmd=(
      "${server_app}-helper"
        "get"
        "server_last_port" "&&"
      "${server_app}-helper"
        "get"
        "server_last_password"
    )
    # dynssh \
    #   -v \
    #   "${_dynssh_opts[@]}" -- \
    #   "${view_target}" \
    #   "${_cmd[*]}" || \
    #   true
    _credentials="$( \
      dynssh \
        "${_dynssh_opts[@]}" -- \
        "${view_target}" \
        "${_cmd[*]}")" || \
      true
    # _msg_info \
    #   "Port and Password: ${_credentials}"
    if [[ "${_credentials}" != "" ]]; then
      _port="$( \
        echo \
          "${_credentials}" | \
          head \
            -n \
            1)"
      _password="$( \
        echo \
          "${_credentials}" | \
          tail \
            -n \
            2)"
      _set_override \
        "server" \
        "port" \
        "${_port}"
      _set_override \
        "view" \
        "password" \
        "${_password}"
    elif [[ "${_credentials}" == "" ]]; then
      _msg_warning \
        "unable to get credentials from view target"
    fi
  elif [[ "${view_target}" == "" ]]; then
    true
  fi
}

_set_overrides() {
  _set_override \
    "view" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "view" \
    "target" \
    ""
  _set_override \
    "view" \
    "address" \
    "localhost"
  _set_override \
    "viewer" \
    "app" \
    "$(_viewer_app_auto_detect)"
  _set_override \
    "server" \
    "app" \
    "$(_server_app_auto_detect)"
  _target_opts_auto_detect
  _set_override \
    "server" \
    "port" \
    ""
  _set_override \
    "view" \
    "port" \
    "59001"
  _set_override \
    "view" \
    "password" \
    ""
  _set_override \
    "view" \
    "length" \
    "$(( 10 * 60 ))" # 10 minutes
    # "$(( 60 * 60 * 24 ))" # 24 hours
  _set_override \
    "poll" \
    "interval" \
    "30"
  _set_override \
    "display" \
    "dim" \
    "n"
  _set_override \
    "touch" \
    "disabled" \
    "n"
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                View date:   $(_get "view" "date")"
  _msg_info "              View target:   $(_get "view" "target")"
  _msg_info "             View address:   $(_get "view" "address")"
  _msg_info "                View port:   $(_get "view" "port")"
  _msg_info "              Server port:   $(_get "server" "port")"
  _msg_info "            View password:   $([[ "$(_get "view" "password")" != "" ]] && echo "****")"
  _msg_info "              View length:   $(_get "view" "length")"
  _msg_info "            Poll interval:   $(_get "poll" "interval")"
  _msg_info "               Viewer app:   $(_get "viewer" "app")"
  _msg_info "               Server app:   $(_get "server" "app")"
  _msg_info "              Display dim:   $(_get "display" "dim")"
  _msg_info "           Touch disabled:   $(_get "touch" "disabled")"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

Opens a VNC session.

Usage:
  $(_get "app" "name")
    [options]
  options:
     -t <view_target>     Target host.
			  Default: $(_get "view" "target")
     -a <view_address>    Address of the VNC server.
			  Default: $(_get "view" "address")
     -p <view_port>       Port of the local VNC server.
			  Default: $(_get "view" "port")
     -P <server_port>     Port of the Remote VNC target.
			  Default: $(_get "server" "port")
     -k <view_password>   Password for the VNC server.
			  Default: $(_get "view" "password")
     -L <view_length>     View length in seconds.
			  Default: $(_get "view" "length")
     -A <viewer_app>      Android VNC viewer app which will be launched.
			  Default: $(_get "viewer" "app")
     -S <server_app>      Destination Android VNC server app.
			  Default: $(_get "server" "app")
     -d                   Whether to dim the screen or not.
			  Default: $(_get "display" "dim")
     -T                   Whether to disable touch or not.
			  Default: $(_get "touch" "disabled")
     -I                   Poll interval for brightness and
                          touch reset in seconds.
			  Default: $(_get "poll" "interval")
     -h                   This message.
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_globals
_global_variables
# shellcheck disable=SC2004
# shellcheck disable=SC2034
while \
  getopts \
    't:a:p:P:k:L:A:S:I:dTcvh?' \
    arg; do
  case \
    "${arg}" in
    t) override_view_target="${OPTARG}" ;;
    a) override_view_address="${OPTARG}" ;;
    p) override_view_port="${OPTARG}" ;;
    P) override_server_port="${OPTARG}" ;;
    k) override_view_password="${OPTARG}" ;;
    L) override_view_length="${OPTARG}" ;;
    A) override_viewer_app="${OPTARG}" ;;
    S) override_server_app="${OPTARG}" ;;
    I) override_poll_interval="${OPTARG}" ;;
    d) override_display_dim="y" ;;
    T) override_touch_disabled="y" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
	 _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0 && \
    _set_overrides && \
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
_set_overrides
_config_user_init \
  "$(_get 'app' 'name')"
app_opts=(
  "$(_get \
       "view" \
       "target")"
  "$(_get \
       "view" \
       "address")"
  "$(_get \
       "view" \
       "port")"
  "$(_get \
       "server" \
       "port")"
  "$(_get \
       "view" \
       "password")"
  "$(_get \
       "view" \
       "length")"
  "$(_get \
       "viewer" \
       "app")"
  "$(_get \
       "server" \
       "app")"
  "$(_get \
       "poll" \
       "interval")"
  "$(_get \
       "display" \
       "dim")"
  "$(_get \
       "touch" \
       "disabled")"
)
_show_config
_android_vnc_viewer \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
